---
- name: Testing being inside and vault
  hosts: dev
  become: false
  gather_facts: false
  vars_files:
    - test.yml

  tasks:

    - name: Test ansible
      ansible.builtin.command:
        cmd: env
      register: _env

    - name: Debug
      ansible.builtin.debug:
        var: _env

    - name: Debug secrets
      ansible.builtin.debug:
        var: password
